import { Booking } from "@/types/booking";
import { Restaurant, Table, LoginResponse } from "./api";
import { AuthUser } from "@/types/user";

export const mockUser: AuthUser = {
    id: 1,
    email: "demo@example.com",
    username: "demo",
    full_name: "Demo User",
    is_active: true,
    is_superuser: false,
    restaurant_id: "1",
    created_at: new Date().toISOString(),
};

export const mockLoginResponse: LoginResponse = {
    access_token: "demo-token",
    token_type: "bearer",
};

export const mockRestaurants: Restaurant[] = [
    {
        id: 1,
        name: "Roya Demo Restaurant",
        description: "A fine dining experience",
        is_active: true,
        operating_hours: {
            monday: { open: "17:00", close: "22:00" },
            tuesday: { open: "17:00", close: "22:00" },
            wednesday: { open: "17:00", close: "22:00" },
            thursday: { open: "17:00", close: "23:00" },
            friday: { open: "17:00", close: "23:00" },
            saturday: { open: "16:00", close: "23:00" },
            sunday: { open: "16:00", close: "22:00" },
        },
    },
];

export const mockTables: Table[] = [
    { id: 1, restaurant_id: "1", table_number: "1", min_capacity: 2, max_capacity: 4, section: "Main", is_active: true },
    { id: 2, restaurant_id: "1", table_number: "2", min_capacity: 2, max_capacity: 4, section: "Main", is_active: true },
    { id: 3, restaurant_id: "1", table_number: "3", min_capacity: 2, max_capacity: 4, section: "Main", is_active: true },
    { id: 4, restaurant_id: "1", table_number: "4", min_capacity: 4, max_capacity: 6, section: "Window", is_active: true },
    { id: 5, restaurant_id: "1", table_number: "5", min_capacity: 4, max_capacity: 6, section: "Window", is_active: true },
    { id: 6, restaurant_id: "1", table_number: "6", min_capacity: 6, max_capacity: 8, section: "Private", is_active: true },
    { id: 7, restaurant_id: "1", table_number: "7", min_capacity: 2, max_capacity: 4, section: "Bar", is_active: true },
    { id: 8, restaurant_id: "1", table_number: "8", min_capacity: 4, max_capacity: 6, section: "Bar", is_active: true },
    { id: 9, restaurant_id: "1", table_number: "9", min_capacity: 8, max_capacity: 12, section: "Private", is_active: true },
    { id: 10, restaurant_id: "1", table_number: "10", min_capacity: 2, max_capacity: 4, section: "Window", is_active: true },
];

const today = new Date().toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const dayAfter = new Date(Date.now() + 172800000).toISOString().split('T')[0];

export const mockBookings: Booking[] = [
    {
        id: 1,
        table_id: 1,
        table: "1",
        date: today,
        time: "18:00",
        duration: 90,
        guests: 2,
        name: "John Doe",
        email: "john@example.com",
        phone: "555-0101",
        status: "confirmed",
        specialRequests: "Window seat if possible",
    },
    {
        id: 2,
        table_id: 4,
        table: "4",
        date: today,
        time: "19:30",
        duration: 120,
        guests: 4,
        name: "Jane Smith",
        email: "jane@example.com",
        phone: "555-0102",
        status: "confirmed",
        specialRequests: "Anniversary",
    },
    {
        id: 3,
        table_id: 2,
        table: "2",
        date: today,
        time: "20:00",
        duration: 90,
        guests: 2,
        name: "Bob Johnson",
        email: "bob@example.com",
        phone: "555-0103",
        status: "new_booking",
    },
    {
        id: 4,
        table_id: 5,
        table: "5",
        date: today,
        time: "17:30",
        duration: 90,
        guests: 4,
        name: "Sarah Williams",
        email: "sarah@example.com",
        phone: "555-0104",
        status: "confirmed",
        specialRequests: "Birthday celebration",
    },
    {
        id: 5,
        table_id: 3,
        table: "3",
        date: today,
        time: "19:00",
        duration: 90,
        guests: 2,
        name: "Michael Brown",
        email: "michael@example.com",
        phone: "555-0105",
        status: "confirmed",
    },
    {
        id: 6,
        table_id: 6,
        table: "6",
        date: today,
        time: "18:30",
        duration: 120,
        guests: 6,
        name: "Emily Davis",
        email: "emily@example.com",
        phone: "555-0106",
        status: "confirmed",
        specialRequests: "Business dinner",
    },
    {
        id: 7,
        table_id: 7,
        table: "7",
        date: today,
        time: "20:30",
        duration: 90,
        guests: 2,
        name: "David Wilson",
        email: "david@example.com",
        phone: "555-0107",
        status: "new_booking",
    },
    {
        id: 8,
        table_id: 8,
        table: "8",
        date: today,
        time: "17:00",
        duration: 90,
        guests: 4,
        name: "Lisa Anderson",
        email: "lisa@example.com",
        phone: "555-0108",
        status: "confirmed",
        specialRequests: "Vegetarian options",
    },
    {
        id: 9,
        table_id: 9,
        table: "9",
        date: tomorrow,
        time: "18:00",
        duration: 120,
        guests: 8,
        name: "Robert Taylor",
        email: "robert@example.com",
        phone: "555-0109",
        status: "confirmed",
        specialRequests: "Large group, need quiet area",
    },
    {
        id: 10,
        table_id: 10,
        table: "10",
        date: tomorrow,
        time: "19:00",
        duration: 90,
        guests: 2,
        name: "Jennifer Martinez",
        email: "jennifer@example.com",
        phone: "555-0110",
        status: "confirmed",
    },
    {
        id: 11,
        table_id: 1,
        table: "1",
        date: tomorrow,
        time: "20:00",
        duration: 90,
        guests: 2,
        name: "Christopher Lee",
        email: "chris@example.com",
        phone: "555-0111",
        status: "new_booking",
    },
    {
        id: 12,
        table_id: 4,
        table: "4",
        date: tomorrow,
        time: "18:30",
        duration: 120,
        guests: 4,
        name: "Amanda White",
        email: "amanda@example.com",
        phone: "555-0112",
        status: "confirmed",
        specialRequests: "Engagement dinner",
    },
    {
        id: 13,
        table_id: 2,
        table: "2",
        date: tomorrow,
        time: "19:30",
        duration: 90,
        guests: 2,
        name: "Daniel Harris",
        email: "daniel@example.com",
        phone: "555-0113",
        status: "confirmed",
    },
    {
        id: 14,
        table_id: 5,
        table: "5",
        date: tomorrow,
        time: "17:30",
        duration: 90,
        guests: 4,
        name: "Michelle Clark",
        email: "michelle@example.com",
        phone: "555-0114",
        status: "new_booking",
        specialRequests: "Allergic to nuts",
    },
    {
        id: 15,
        table_id: 7,
        table: "7",
        date: tomorrow,
        time: "20:30",
        duration: 90,
        guests: 2,
        name: "James Lewis",
        email: "james@example.com",
        phone: "555-0115",
        status: "confirmed",
    },
    {
        id: 16,
        table_id: 3,
        table: "3",
        date: dayAfter,
        time: "18:00",
        duration: 90,
        guests: 2,
        name: "Patricia Walker",
        email: "patricia@example.com",
        phone: "555-0116",
        status: "confirmed",
    },
    {
        id: 17,
        table_id: 6,
        table: "6",
        date: dayAfter,
        time: "19:00",
        duration: 120,
        guests: 6,
        name: "Matthew Hall",
        email: "matthew@example.com",
        phone: "555-0117",
        status: "confirmed",
        specialRequests: "Corporate event",
    },
    {
        id: 18,
        table_id: 8,
        table: "8",
        date: dayAfter,
        time: "20:00",
        duration: 90,
        guests: 4,
        name: "Nancy Allen",
        email: "nancy@example.com",
        phone: "555-0118",
        status: "new_booking",
    },
    {
        id: 19,
        table_id: 9,
        table: "9",
        date: dayAfter,
        time: "18:30",
        duration: 120,
        guests: 10,
        name: "Kevin Young",
        email: "kevin@example.com",
        phone: "555-0119",
        status: "confirmed",
        specialRequests: "Family reunion",
    },
    {
        id: 20,
        table_id: 10,
        table: "10",
        date: dayAfter,
        time: "19:30",
        duration: 90,
        guests: 2,
        name: "Laura King",
        email: "laura@example.com",
        phone: "555-0120",
        status: "confirmed",
        specialRequests: "First date",
    },
];
